server:
  port: 8002

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8000/eureka/

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 192.168.0.58
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 2000ms
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  application:
      name: cloudStorage-service
logging:
  level:
    root: info
#  path: E:\log
#  file: E:\log\cloud_storage.log
